### ISSUE TITLE
Upgrading Ansi Con failed in my Eclipse instance

### ISSUE THREAD

**Issue by ccanaria** [mihnita/ansi-econsole#17]
I tried couple of times to upgrade it but I always got this error: "An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,net.mihai-nita.ansicon.plugin,1.3.1.201508091828
No repository found containing: org.eclipse.update.feature,net.mihai-nita.ansicon,1.3.1.201508091828"

I have: Eclipse Java EE IDE for Web Developers.
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

I also tried uninstalling the previous version and installing the current one in the repo, but still I get this error. Now I dont have AnsiCon in my Eclipse :(

I looekd at my log and here's a more detailed entry:

!ENTRY org.eclipse.equinox.p2.engine 4 4 2015-09-30 20:28:02.180
!MESSAGE An error occurred while collecting items to be installed
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2015-09-30 20:28:02.181
!MESSAGE session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2015-09-30 20:28:02.181
!MESSAGE No repository found containing: org.eclipse.update.feature,net.mihai-nita.ansicon,1.3.1.201508091828
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2015-09-30 20:28:02.181
!MESSAGE No repository found containing: osgi.bundle,net.mihai-nita.ansicon.plugin,1.3.1.201508091828

**Comment by mihnita** [comment]
Hi ccanaria,

I am sorry for you troubles, and thanks for reaching out to file a bug, rather than just abandon it.

Trying to see what's wrong, but (at least for now) I can't reproduce it.
I have also checked the server logs for the last 10 days, nothing suspicious...

But it looks like it is not uncommon, and not necessarily the problem of the plugin:
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=290782
* https://www.eclipse.org/forums/index.php/t/1026052/
* http://stackoverflow.com/questions/6470802/what-to-do-about-eclipses-no-repository-found-containing-error-messages

The post on stackoverflow suggest this:
  1. you have to remove and re-add the Eclipse Project Update site, so that its metadata are re-calculated.
  2. is to edit the pre-defined URL link by adding just a trailing “/” to the update site URL.
  3. do nothing, but to uncheck the 'Contact all update sites during install to find required software'  before checking the URL link.

My best bet is 1 (looks like 2 is a variation of it...)

So can you please remove the plugin site and then add it back?
* Help -> Install New Software... -> the "Available Software Sites" link, select the Ansicon site and remove it
* Add it back the way you did it first time (no need to do that if you install from Marketplace)

Thank you very much,
(and please let me know if one of the workarounds solves the problem)
Mihai

**Comment by ccanaria** [comment]
Thank you Mihai for your response. I finally able to re-install it usign 
the solution from this stackoverflow post: 
http://stackoverflow.com/questions/6470802/what-to-do-about-eclipses-no-repository-found-containing-error-messages

**Comment by mihnita** [comment]
Thank for the update, glad it is solved.
Regards,
Mihai

**Comment by SylkeWay** [comment]
After I removed mihai nita's update site, the problem went away.

I don't know why STS put ansi-console as one of the plug-ins.It was safe to remove it since I have no idea what it even does.

This problem is occurring as recently with the STS 3.7.3/E4.6 which I downloaded a week ago. The eclipse bug is failing to skip uncertified/unavailable update sites. Which means an unbuggy Eclipse should have skipped it anyway, I might as well simply removed it.
