### ISSUE TITLE
Colors mismatch when scrolling

### ISSUE THREAD

**Issue by sbellus** [mihnita/ansi-econsole#3]
See attached pictures.

After scrolling, lines above colored lines have same color.
This color is also remembered and when new build is started, text color is red.

First build:
![firstprint](https://f.cloud.github.com/assets/436473/2039289/a451f14c-899e-11e3-9276-a35ac548eecc.png)

After scrolling:
![afterscrollingup](https://f.cloud.github.com/assets/436473/2039290/ae4165c0-899e-11e3-97fb-b2b073bf7f71.png)

**Comment by calvertdw** [comment]
@VsevolodGolovanov Were you able to accomplish this using a logging framework? I am trying to figure out how to do that with log4j2.

**Comment by calvertdw** [comment]
Black text is no longer readable in a console with a black background. I think you must use "uncolored" text for black/white.

**Comment by VsevolodGolovanov** [comment]
@calvertdw, the formatter doesn't hardcode any colors, just repeats what's configured on every line. It's up to you to configure the proper colors. E.g. our config is

    <property name="colors" value="severe:brightred,fatal:brightred,error:brightred,warn:red,warning:red,info:cyan,config:cyan,debug:blue,fine:blue" />

`trace` isn't configured, so yeah it's uncolored and shows black or white depending on the console background color.

**Comment by kutschkem** [comment]
Maybe you are just not using the best extension point for what you are trying to achieve.

I used [consolePatternMatchListeners](https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fui%2Fconsole%2FIPatternMatchListener.html) once to look for stack traces (so multiline pattern!) in console output. I don't remember exactly what I did with it, but I think you could hook into this to look for the ranges between color escapes and the reset codes, and color the text in between. This gets you access to the whole console output, not just one line at a time. The scrolling issue basically solves itself because of that as well.

**Comment by mihnita** [comment]
Fixed by version 1.4.0.202001252332
