### ISSUE TITLE
Why not considering to contribute an ANSI support to the default eclipse console ?

### ISSUE THREAD

**Issue by sbernard31** [mihnita/ansi-econsole#35]
Have you already try/think to contribute your code in this form or in a more adapted way to the eclipse platform project ?

If yes, I suppose that was a failure as we still not have an ANSI support by default in eclipse, could you tell what happened ?
If no, is there any reasons about that ?

It seems there are community needs about that for a long time and the [associated bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=112948) is marked as "help-wanted".

Being able to directly modify code in the platform could even make this bug #3 fix easier ?

**Comment by sbernard31** [comment]
Platform committers sounds open for a contribution about that :
https://bugs.eclipse.org/bugs/show_bug.cgi?id=112948#c21

**Comment by mihnita** [comment]
I have though about it, a long time ago...
Didn't pursue because of

1. Laziness
Afraid it will be too "bureaucratic" and I will have to jump through all kind of hoops, approvals, reviews, etc. :-)

2. Not being able to push fixes / new features fast enough.
Now it is a lot more stable, so that would not be a problem

3. It seems to me that the TM Terminal plugin would be a way better starting point
It feels like a real terminal, and understand more ANSI escapes, including clear screen, cursor positioning, etc.
Some of them can't even be supported with the Eclipse default console (very different model)
Would need some work to make it a "default console" from the Launcher, somehow.
Not sure what that would take. And it's not my plugin anyway :-)

----

I will "ping" the bug you linked to and offer to contribute my code to Eclipse, if they are fine with the limitations (the fact that it can't really support cursor movement, probably never)

Being able to fix my bug #3 would be a nice bonus...

Thanks for the "kick in the behind" :-)
It might be a step forward :-)

**Comment by mihnita** [comment]
Giving up, for the reasons I gave in Oct 2018.
I've fixed bug #3 "my own way", and I made the plugin faster.
So there is no major benefit to have it in Eclipse other than discoverability (pushing my stuff on everybody).
But why do that? "Install if you want" is friendlier.
