### ISSUE TITLE
Presence of plugin forces "[--spring.output.ansi.enabled=always]" on command line

### ISSUE THREAD

**Issue by davidmichaelkarr** [mihnita/ansi-econsole#36]
I don't use this plugin, but I work with some other developers who apparently had it installed, but very likely because of some other set of plugins they installed (spring ide, for instance).

We work on a Spring Boot application that normally doesn't take command-line arguments.  I added some alternative diagnostic code that is run when any command-line arguments are found, and then it exits.  This all worked fine on my desktop and on the test servers.

Some developers reported that when they were trying to run the service in Eclipse, they were getting into this code that only runs when command-line arguments are sent, but they weren't sending any command-line arguments.  I checked their run configuration, and they had no command-line arguments.

I then set a breakpoint and ran in debug to see what was happening.  When it got to the point of checking for command-line arguments, I found the following value:

> [--spring.output.ansi.enabled=always]

I saw some configuration settings for the plugin, and I turned them all off.  No change.  I then uninstalled this plugin.  That fixed the problem. I've recommended to the developers that they uninstall this plugin for now.

**Comment by mihnita** [comment]
The plugin does not touch the command line, it is probably some spring plugin.
You can check the sources. And the fact that the flag is --spring.* is another indication.

On the other side, I would blame (a bit :-) your application.
"Do something if there is anything in the command line" feels a bit unfriendly.
And advising people to uninstall a usefull plugin because your own application is "intollerant" to input feels a bit much.

But, of course, I can't stop you, you can give whatever advice you want.
There is nothing I can fix, but you can change your app to be friendlier.
If not, you are forcing your users to make a choice between 2 things that they like (your app and my plugin)

But please don't blame it on this plugin.

**Comment by davidmichaelkarr** [comment]
I have no idea what is to "blame".  I know that devs on the team were getting this error, and I was not. I looked at what was different in their config.  I removed this plugin as I didn't see it in my config. It fixed their problem. I have no idea what the root cause is, but the presence of this plugin caused it, directly or indirectly.

**Comment by mihnita** [comment]
"blame" was the wrong word...

The way I see it, the problem is a mixture of 3 different things.
Changing one any one of them might fix the it issue.

1. My plugin has nothing to do with that flag at all (as you can see by searching the code).
It only takes the ANSI escapes and render the text with the proper color.
2. The Eclipse console does not answer as a real terminal, so by default ANSI output is disabled
That flag forces the output of the escape.
I don't know if the Spring Boot plugin (or the developers?) add the spring.output.ansi.enabled flag.
From some searches it looks like it is the developers.
Or the Spring Boot plugin detects that my plugin is installed, and says "we can set the flag. the
Eclipse console is wrong, ANSI escape are supported"
3. You app looks for command line parameters and does its thing

By uninstalling my plugin ANSI support goes away, so Spring says "there is no point to force ANSI anymore", does not add the flag, and "solves" the problem.

But my plugin is the one that has the least control. There is no change that I can make to fix this.
So it is not a bug that I can fix.

What can be some better fixes?

1. See who adds the flag. 
   1.a If it is the developers, ask them to remove that flag when running your app
   1.b. If it is added by the Spring Boot plugin, file a bug with that
2. Change your app to not dump info + exit if there are any arguments, but only for a certain argument
  Instead of something like
      if (argv.length > 1) dumpAndExit()
  do something like
      for (String arg : argv)
          if (arg.equals("--dump"))
                dumpAndExit()

I think that option 2 is easier, and under you control.
If developers add the flag (1.a) that is also easy to fix.

A Spring boot plugin change (1.b) would have implications for many many people.
And you depend on that team for a fix.

Sure, you can uninstall my plugin.
But that adds color functionality for everything, not just Spring.
And I would assume that people like colored output :-)
Taking that away, seems like overkill, when a small change in your app would solve everything.

**Comment by mihnita** [comment]
I've downloaded and installed the latest Spring Tool Suite 4 (4.0.1.RELEASE)
It added the flag to a new demo app created using the wizard.

So the flag is not added by developers, it is Spring Tool Suite.
The "secret" is in the runner.

From the main menu try "Run" -- "Run Configurations..." -- select the runner for your application -- select the first tab, "Spring Boot" -- uncheck the "ANSI console output" checkbox.

That will remove the flag.

This solution does not require any code change, and does not remove color support from all applications, only yours.
But if you want color logging in your own app then my option (checking for certain flag) works.

If you want something that reacts to all arguments, so that users don't have to know some "special dump flag" then just check and ignore that special flag:
```
for (String arg : args) {
	if (!arg.startsWith("--spring.output.ansi.enabled"))
		dumpAndExit();
}
```

**Comment by mihnita** [comment]
Not an ansi-console issue.
Some solutions offered.
