### ISSUE TITLE
not workign with Spring Tool suite 4

### ISSUE THREAD

**Issue by ieleuthe** [mihnita/ansi-econsole#37]
Your plugin has worked wonderfully till recently when it stopped coloring the logs for Spring Tool Suite 4

Check on this.
http://tinypic.com/r/jztn6g/9

After uninstalling it showed as expected. 
(Reinstalling plugin through marketplace did not solve this)

**Comment by mihnita** [comment]
_"After uninstalling it showed as expected."_

I suppose that this means "the extra characters don't show anymore"
But is the output colored, or not?

**Comment by mihnita** [comment]
I've downloaded and installed the latest Spring Tool Suite 4 (4.0.1.RELEASE), and created a small demo app (using the default wizard)

It all works well.
But the thing that I think might be an explanation for the screenshot is that the plugin is disabled.

Can you please check the top-right of the output console? (where all the icons are, "minimize", "maximize", "remove Launch" etc.)

When my plugin is install there should be an icon there that looks like a blue C with a red A inside it.
If the icon is gray instead of colored it means my plugin is disabled.

Click the icon (the icon should be colored) and run your app.
Now the output should be colored, and the "weird characters" (that are ANSI escapes) should not show anymore.

**Comment by ieleuthe** [comment]
I removed the settings re downloaded the add on and enabled the ansi and works as expected

**Comment by mihnita** [comment]
Thanks for the update.
