### ISSUE TITLE
Coloring doesn't work in 2020-03

### ISSUE THREAD

**Issue by leomayer** [mihnita/ansi-econsole#49]
With the new Eclipse the Console isn't any longer colored. Perhaps there is an option gone?

**Comment by mihnita** [comment]
I've tested it, and work on my machines.

But I know this is not good enough :-)
Can you give a bit more details that might help me reproduce this?

Some ideas:
* OS and OS versions?
* Can you see the enable / disable icon at the top-right of the console?
* Can you see "Ansi Console" in Preferences? Does that panel seem to work?
* If you go to About Eclipse and click "Installation details" can you see it in the "Installed Software" tab? What version?

Thank you,
Mihai

**Comment by psyray** [comment]
Same problem for me, no more color in console
If I deactivate Ansi console, there is no ANSI code in console.
In Run/Debug > Console preference, there is an option, turn out or in makes no difference
![image](https://user-images.githubusercontent.com/1230954/78256372-ba07b480-74f8-11ea-85d3-ca0d82917a78.png)

OS : Linux Mint
OS Version : 19.3 Tricia
Eclipse : 2020-03 (4.15.0)
Enable/disable icon is present
Ansi console is present in preferences
Ansi console version : 1.4.2.202002090224

**Comment by mihnita** [comment]
Thank you for the extra info...

But it there are still some "pieces of the puzzle" missing :-)
And if you enable / disable / enable the plugin, does it solve things?
I've noticed that in some cases the update causes the preferences to get "out of sync" with the icon. The icon looks enabled, but in reality the plugin is disabled. Trying to enable/disable a couple of times brings things in sync.

I don't have a Mint around, but I've tried it on Ubuntu & Debian, seems fine.
I will install a Mint and try...

Anything else that you can think of? Maybe some other plugin that messes with the colors in the console? Something like https://marketplace.eclipse.org/content/logviewer ?

Sorry, I'm not saying this plugin is perfect, but I need to find a way to reproduce this in order to fix it :-)
