### ISSUE TITLE
Fix icon background (white dots)

### ISSUE THREAD

**Issue by vogella** [mihnita/ansi-econsole#52]
Reported to STS but it seems to belong here: 

https://github.com/spring-projects/sts4/issues/472#issuecomment-637643570

**Comment by mihnita** [comment]
Thanks.

I already knew what the problem (long ago), but didn't have a fix.
When I started this plugin I thought that the only possible formats for icons were `.gif` and `.jpg`, and `.gif` was the only one with transparency. But there is only 1 bit of transparency, meaning "jagged" edges. And was also at the time when Eclipse didn't have a dark mode, so it was ok.

But times changes :-)
I can replace the icons with `.png`, but...

There is a bigger change that I have in the pipeline, fixing (among others) issue https://github.com/mihnita/ansi-econsole/issues/45.
It uses the standard Eclipse mechanism for enabled/disabled icons (right now I use 2 icons of my own, and change them). Eclipse takes the enabled icon and "disables" it algorithmically, using some kind of overlay.
The difference between states is not as visible as it is now, and I don't like it, but it is standard Eclipse, instead of my own hack.

**Comment by mihnita** [comment]
Fixed and released.
