### ISSUE TITLE
Provide source bundle for updatesite

### ISSUE THREAD

**Issue by laeubi** [mihnita/ansi-econsole#58]
currently the update-site only contains the compiled sources, it would be nice if source bundles are also provided to make development easier.

**Comment by mihnita** [comment]
Sorry, I am not very familiar with that.
I know that there are some configuration stuff in Eclipse about the sources of the plugin.

But I think that everything is in GitHub.
If you clone the project the sources of the plugin are in `AnsiConsole` folder, the feature description in `AnsiConFeature`, and the sources of the update site are in the `AnsiConSite` folder.

Is that what you are looking for, or is there something else?
Where can I read about it?

Thanks,
M.

**Comment by laeubi** [comment]
As you are using Tycho, it allows to generate the most stuff for this so you don't need to do much: there are some examples here:
https://wiki.eclipse.org/Tycho/Reference_Card#Source_Bundles
https://wiki.eclipse.org/Tycho/Reference_Card#Source_Features

**Comment by mihnita** [comment]
Ah, I see.

Thing is, I'm not using Tycho.
I've tried a (long) while ago, but it required a relatively new version of Eclipse, if I remember well.

Right now I still support Neon. I keep a version around, and old JDK 8, just for this :-)
So I prepare the release from the Eclipse GUI (Neon + JDK 8).
Then test on newer Eclipse versions, then Win / macOS / Linux, before pushing it out.
Then git tag the repository it and push it (if you run `git tag` you see the exact release points)

So what you see in this repo is all I have.

---

Should I take another look at Tycho?
Maybe... but I don't release often enough to be a pain :-)

**Comment by laeubi** [comment]
Is there any rationale in supporting ancient eclipse versions? anyways you should be able to build with tycho targeting old eclipse releases/java8 latest tycho just need java11 to run. Especially the pomless build was improved making using tycho a lot easier.

 But I think if you export from the IDE there should also be an option to export the sources:

![grafik](https://user-images.githubusercontent.com/1331477/105969525-a54c6c80-6088-11eb-8036-fe92f7d0e365.png)

**Comment by mihnita** [comment]
> Is there any rationale in supporting ancient eclipse versions?

I've checked the HTTP request logs since Dec 1, 2020 (last 2 months)
About 6% of the requests still come from "ancient" Eclipse versions (mars, oxygen, neon, photon)
I'm not using any fancy new APIs that are not supported on older versions.
So why intentionally break these people (about 300)?

> anyways you should be able to build with tycho targeting old eclipse releases/java8 latest tycho just need java11 to run. 

That's another one :-)
29% of the requests come from Java 8.
Yes, in theory you can generate JDK 8 class files with Java 11.
But it is possible to call methods and use classes from the Java 11 runtime, and there is no good validation for that.
The .class files will still be generated "for Java 8", but fail to run.
I've seen this in a different project.

See here, better explained:
https://bugs.openjdk.java.net/browse/JDK-8058150

To prevent that I can run another tool that checks for that.
But that's just adding more complexity.
It is just easier to compile with 8.

Again, I'm not releasing often enough to be a pain.

---

Generating sources from GUI: yes, I'm looking into that.
But probably over the week-end.
Meantime I have a full time job, and the sources are available, if someone needs them :-)

**Comment by laeubi** [comment]
No need to hurry, you can configure tycho to use a java-8 jdk for compilation, verification just in case your bored of exporting it from the UI :-)

**Comment by mihnita** [comment]
Everything should be in.

I don't think I would release just for this.
But I'll check what other fixes / enhancements I did since releasing 1.4.3 and see if it is work a release.
Anyway, next time it will be there, unless you have some urgent need.

Thanks a lot,
Mihai

**Comment by mihnita** [comment]
Fixed. Will be in the next release.

**Comment by laeubi** [comment]
Nothing urgent, I'm just reworking the [eclipse-cucumber plugin](https://github.com/cucumber/cucumber-eclipse) and it can benefit from a color console but at them moment everything works fine!

**Comment by mihnita** [comment]
Can you do that without sources?

Would it help if I re-release  the older version (the one that is already out), with sources?
(I can make it happen by "messing up" with the XMLs files by hand :-)

**Comment by laeubi** [comment]
Sure sources are optional, if its too much hassle at the moment, feel free to delay it to some later point in time (e.g. if you are doing a release anyways).

**Comment by mihnita** [comment]
I think I am done with what I wanted to do for a new release:
* fixed this issue
* fixed issue #57
* fixed issue #58
* fixed issue #46
* fixed issue #45

In order to fix issue #45 I had to migrate from actions (deprecated) to commands, which is something I wanted to do for a long time. But it forces me into giving up control on the enabled / disabled colors. Eclipse controls that... and I don't like the result.
But it is what it is...

I intend to test a bit more and release over the week-end.

If you want to play with it a bit early you can install from here (version 1.4.4.202102040736):
  https://www.mihai-nita.net/eclipse_test

**Comment by mihnita** [comment]
Released.
